name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
    - name: Restore NuGet packages
      run: nuget restore amadeus-csharp.sln
    - name: Build the Solution
      run: | 
        msbuild amadeus-csharp.sln /p:Configuration=Release
    - name: Run Tests
      run: vstest.console.exe .\tests\amadeus-test\bin\Release\amadeus-csharp.Tests.dll
