name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore NuGet packages
      run: nuget restore amadeus-csharp.sln
    - name: Build the Solution
      run: | 
        msbuild amadeus-csharp.sln /p:Configuration=Release
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.12.0 -DirectDownload -OutputDirectory .
    - name: Run UnitTests
      run: packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe .\amadeus-test\bin\Debug\amadeus-test.dll
