name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ '2.1.x' ]
        os: [windows-latest]
    defaults:
      run:
        shell: pwsh
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} with .NET ${{ matrix.dotnet-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: | 
        dotnet add amadeus-test package Newtonsoft.Json
        dotnet add amadeus-test package Castle.Core
        dotnet add amadeus-test package System.Runtime.CompilerServices.Unsafe
        dotnet add amadeus-test package System.Threading.Tasks.Extensions
        dotnet add amadeus-test package Moq 
    - name: Resetting nuget
      run: |
        dotnet clean -c Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
